CREATE TABLE IF NOT EXISTS Medico
(
	CRM INT NOT NULL,
	NomeMedico VARCHAR(60) NOT NULL,
	TelefoneMedico VARCHAR(15),
	Percentual FLOAT,
	PRIMARY KEY (CRM)
);

CREATE TABLE IF NOT EXISTS Agenda
(
	IdAgenda INT NOT NULL PRIMARY KEY,
	DiaSemana VARCHAR(20) NOT NULL,
	HoraInicio TIME NOT NULL,
	HoraFim TIME,
	CRM INT NOT NULL,
	FOREIGN KEY (CRM) REFERENCES Medico(CRM) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Especialidade
(
	IdEspecialidade INT NOT NULL PRIMARY KEY,
	NomeEspecialidade VARCHAR(50) NOT NULL,
	Indice FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS ExerceEspecialidade
(
	CRM INT NOT NULL,
	IdEspecialidade INT NOT NULL,
	PRIMARY KEY (CRM, IdEspecialidade),
	FOREIGN KEY (CRM) REFERENCES Medico(CRM) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (IdEspecialidade) REFERENCES Especialidade(IdEspecialidade) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Paciente
(
	IdPaciente INT NOT NULL PRIMARY KEY,
	CPF BIGINT NOT NULL UNIQUE,
	NomePaciente VARCHAR(60) NOT NULL,
	TelefonePaciente VARCHAR(15),
	Endereco VARCHAR(255) NOT NULL,
	Idade INT NOT NULL,
	Sexo VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS Consulta
(
	IdConsulta INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CRM INT NOT NULL,
	IdEspecialidade INT NOT NULL,
	IdPaciente INT NOT NULL,
	Data DATE NOT NULL,
	HoraInicio TIME NOT NULL,
	HoraFim TIME NOT NULL,
	Pagou INT NOT NULL,
	ValorPago FLOAT DEFAULT 0,
	FormaPagamento VARCHAR(20) NOT NULL,
	FOREIGN KEY (CRM) REFERENCES Medico(CRM) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (IdEspecialidade) REFERENCES Especialidade(IdEspecialidade) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (IdPaciente) REFERENCES Paciente(IdPaciente) ON UPDATE CASCADE ON DELETE CASCADE,
	CONSTRAINT cPagou CHECK (Pagou IN (0, 1))
);

CREATE TABLE IF NOT EXISTS Diagnostico
(
	IdDiagnostico INT NOT NULL PRIMARY KEY,
	TratamentoRecomendado VARCHAR(300),
	RemedioReceitados VARCHAR(300), 
	Observacoes VARCHAR(300),
	IdConsulta INT NOT NULL,
	FOREIGN KEY (IdConsulta) REFERENCES Consulta(IdConsulta) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Doenca
(
	IdDoenca INT NOT NULL PRIMARY KEY,
	NomeDoenca VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Diagnostica
(
	IdDiagnostico INT NOT NULL,
	IdDoenca INT NOT NULL,
	PRIMARY KEY (IdDiagnostico, IdDoenca),
	FOREIGN KEY (IdDiagnostico) REFERENCES Diagnostico(IdDiagnostico) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (IdDoenca) REFERENCES Doenca(IdDoenca) ON UPDATE CASCADE ON DELETE CASCADE
);
